### ISSUE TITLE
ui font alignment

### ISSUE THREAD

**Issue by withlin** [kubegems/dashboard#49]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/22409551/166688762-75d573d0-d3cf-4671-92e2-4d90d9e4ec8c.png">

when type f12 will be happened.

**What you expected to happen**:
font should alignment

**How to reproduce it (as minimally and precisely as possible)**:
when type f12 will be happened.

**Anything else we need to know?**:

**Comment by chenshunliang** [comment]
this is ui bug, we will fix it  in next version, thanks for your issue. @withlin :clap:
