### ISSUE TITLE
[Observ] Add Dial of` HTTP.GET` pannel

### ISSUE THREAD

**Issue by LinkMaq** [kubegems/dashboard#519]
Include basic informations of http

![Image](https://user-images.githubusercontent.com/2688646/211502967-e2877749-5530-4981-978a-f5c4e8279e0d.png)

**Comment by LinkMaq** [comment]
https:   probe_http_ssl{instance}
version:  probe_http_version
tlsversion:  probe_tls_version_info{version}
cert expiry: probe_ssl_earliest_cert_expiry

**Comment by chenshunliang** [comment]
Supported at this commit https://github.com/kubegems/dashboard/commit/3540ff43f92b80428c36965328e7801a0487318a
