### ISSUE TITLE
README.md context word spell error

### ISSUE THREAD

**Issue by ISADBA** [kubegems/dashboard#528]
url:  https://github.com/kubegems/dashboard
source content: git clone https://github.com/kubegems/**dsahboard.**git
correct content：  git clone https://github.com/kubegems/dashboard.git

**Comment by chenshunliang** [comment]
thanks for your issue, we will fix it.

**Comment by chenshunliang** [comment]
fixed at https://github.com/kubegems/dashboard/commit/8b9e443986f1cb72b09ef809da1b8685837bf933.   @ISADBA

**Comment by ISADBA** [comment]
👍
