### ISSUE TITLE
Put the bootstrap to import cluster in a more obvious place

### ISSUE THREAD

**Issue by tpiperatgod** [kubegems/dashboard#589]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

I cannot find the bootstrap to import my cluster when I login to the dashboard. 

<img width="521" alt="image" src="https://user-images.githubusercontent.com/2360535/223003046-20a84851-c190-46a6-b741-82011a7bfd05.png">

**What you expected to happen**:

I would suggest putting the bootstrap in a more obvious place.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by chenshunliang** [comment]
Sorry, we have not provided a guide interface for the time being, and we will push forward as soon as possible. You can also currently view adding tutorials from the kubegems.io documentation.

**Comment by chenshunliang** [comment]
this supported in this commit https://github.com/kubegems/dashboard/pull/600
